export enum SensorType {
  GENERIC = 'GENERIC',
  AMBIENT_TEMP = 'Ambient temperature',
  WATER_TEMP = 'WATER_TEMP',
  HUMIDITY = 'HUMIDITY',
  EC = 'EC',
  PH = 'PH',
  LIGHT = 'LIGHT',
  INTERNAL_WATER_FLOW = 'INTERNAL_WATER_FLOW',
  WATER_LEVEL = 'WATER_LEVEL',
  MAIN_WATER_VALVE = 'MAIN_WATER_VALVE'
}
